#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# install_circleci_runner.sh
#
# Installs CircleCI's self-hosted "machine runner 3" on the VM by using
# the official packagecloud apt repository. Intended to be invoked by
# Vagrant with CIRCLECI_RUNNER_TOKEN set.
#
# Idempotent. Re-running will:
#   - skip the apt repo setup if already present
#   - reinstall/upgrade the circleci-runner package
#   - rewrite the config file with the current token
#   - restart the service
# -----------------------------------------------------------------------------
set -euo pipefail

log() { printf '[circleci-runner] %s\n' "$*"; }
die() { printf '[circleci-runner][ERR] %s\n' "$*" >&2; exit 1; }

TOKEN="${CIRCLECI_RUNNER_TOKEN:-}"
RUNNER_NAME="${CIRCLECI_RUNNER_NAME:-$(hostname)}"
CONFIG_DIR="/etc/circleci-runner"
CONFIG_FILE="${CONFIG_DIR}/circleci-runner-config.yaml"
WORKDIR="/var/lib/circleci-runner/workdir"
RUNNER_USER="circleci"   # created by the .deb postinst

if [ -z "$TOKEN" ]; then
  die "CIRCLECI_RUNNER_TOKEN is not set. Pass it via Vagrant env, e.g.:
       PowerShell:  \$env:CIRCLECI_RUNNER_TOKEN = 'xxxx'
       then:        vagrant provision --provision-with circleci-runner"
fi

export DEBIAN_FRONTEND=noninteractive

# -----------------------------------------------------------------------------
# 1. Add the packagecloud apt repo for CircleCI runner (idempotent).
# -----------------------------------------------------------------------------
REPO_LIST="/etc/apt/sources.list.d/circleci_runner.list"
if [ ! -f "$REPO_LIST" ]; then
  log "Adding packagecloud apt repository for circleci/runner..."
  apt-get update -qq
  apt-get install -y -qq curl gnupg ca-certificates apt-transport-https
  curl -fsSL "https://packagecloud.io/install/repositories/circleci/runner/script.deb.sh?any=true" \
    | bash
else
  log "packagecloud repo already present -- skipping"
fi

# -----------------------------------------------------------------------------
# 2. Install / upgrade the runner package.
# -----------------------------------------------------------------------------
log "Installing circleci-runner package..."
apt-get update -qq
apt-get install -y -qq circleci-runner

# -----------------------------------------------------------------------------
# 3. Ensure the circleci service user can actually run docker. The .deb
#    creates the `circleci` user but does NOT add it to the `docker` group.
#    Without this, the deploy job can't run `docker compose` and fails
#    with "permission denied on /var/run/docker.sock".
# -----------------------------------------------------------------------------
if id "$RUNNER_USER" >/dev/null 2>&1; then
  if ! id -nG "$RUNNER_USER" | tr ' ' '\n' | grep -qx docker; then
    log "Adding $RUNNER_USER to docker group"
    usermod -aG docker "$RUNNER_USER"
  fi

  # The deploy job writes /opt/deploy/env/*.env and runs docker compose
  # there. configure_user.sh created /opt/deploy owned by vagrant:vagrant;
  # hand ownership to the circleci user so the deploy job doesn't need sudo.
  if [ -d /opt/deploy ]; then
    log "Granting $RUNNER_USER ownership of /opt/deploy"
    chown -R "${RUNNER_USER}:${RUNNER_USER}" /opt/deploy
  fi
fi

# -----------------------------------------------------------------------------
# 4. Write the runner config. Token is secret; file is 0600 root:circleci.
# -----------------------------------------------------------------------------
install -d -m 0755 "$CONFIG_DIR"
install -d -m 0755 -o "$RUNNER_USER" -g "$RUNNER_USER" "$WORKDIR"

log "Writing ${CONFIG_FILE}"
# NOTE: we intentionally do NOT set `working_directory`. The runner has a
# sensible default (it generates a unique per-task path). When we tried
# "${WORKDIR}/%s" the %s placeholder was not substituted, leaving a
# literal `%s` directory that broke docker compose (invalid URL escape).
cat > "${CONFIG_FILE}" <<EOF
# Generated by install_circleci_runner.sh -- do not edit by hand.
api:
  auth_token: "${TOKEN}"

runner:
  name: "${RUNNER_NAME}"
  cleanup_working_directory: true
EOF
chown root:"${RUNNER_USER}" "${CONFIG_FILE}"
chmod 0640 "${CONFIG_FILE}"

# -----------------------------------------------------------------------------
# 5. Enable & (re)start the service installed by the .deb.
# -----------------------------------------------------------------------------
systemctl daemon-reload
systemctl enable circleci-runner.service >/dev/null
systemctl restart circleci-runner.service

sleep 3
if systemctl is-active --quiet circleci-runner.service; then
  log "circleci-runner is active."
  log "Logs:    sudo journalctl -u circleci-runner -f"
  log "Status:  sudo systemctl status circleci-runner"
else
  log "Service is NOT active. Dumping status:"
  systemctl status circleci-runner.service --no-pager || true
  die "Runner failed to start. Check logs above."
fi
